import { Project } from "../../types";

export const ARDA_PROJECT: Project = {
  id: "arda",
  slug: "arda",
  name: "ARDA Platform",
  organization: "ARDA Labs",
  role: "Lead Architect & Core Builder",
  period: "2024 – Hiện tại",
  year: "2024",
  summary:
    "Nền tảng Cloud-native multi-tenant FinOps & Enterprise SaaS với kiến trúc 9 Go Microservices, React Module Federation (1 Shell + 7 Remotes), IAM Ory Kratos/Hydra, và cụm 3-node K3s tự vận hành.",
  problem:
    "Các hệ thống SaaS quản trị tài chính & vận hành doanh nghiệp thường gặp khó khăn khi mở rộng theo chiều ngang, phụ thuộc vào monolithic backend, và giao diện cồng kềnh khó chia tách quyền sở hữu theo từng module.",
  techStack: [
    "Go",
    "gRPC",
    "Protobuf",
    "NATS JetStream",
    "React",
    "Module Federation",
    "TypeScript",
    "Tailwind CSS",
    "shadcn/ui",
    "PostgreSQL",
    "CloudNativePG",
    "Ory Kratos",
    "Ory Hydra",
    "Kubernetes (K3s)",
    "Traefik",
    "ArgoCD",
    "Cloudflare Tunnel",
    "Zeebe BPMN",
  ],
  domains: ["FinOps", "Enterprise SaaS", "Microservices", "Cloud-native", "Distributed Systems", "IAM & Auth"],
  competencies: [
    "Microservices Architecture (Go + gRPC + NATS)",
    "Micro-Frontend Architecture (React Module Federation)",
    "Advanced Authentication & IAM (Ory Kratos, Hydra OAuth2/OIDC)",
    "Event-Driven Architecture & Transactional Outbox",
    "Self-hosted Kubernetes & High Availability DB (CloudNativePG)",
    "GitOps Declarative Infrastructure (ArgoCD)",
  ],
  architecture: [
    "Backend Monorepo (arda-be): 9 Go microservices độc lập (iam, platform, finance, workflow, crm, hrm, notification, media, mdm) giao tiếp đồng bộ qua gRPC nội bộ và bất đồng bộ qua NATS JetStream.",
    "Data Consistency: Sử dụng Transactional Outbox Pattern kết hợp thư viện Go nội bộ (arda-events, arda-postgres) để đảm bảo tính nhất quán dữ liệu phân tán không bị mất mát message.",
    "Frontend Monorepo (arda-mfe): React Module Federation gồm 1 Shell quản trị routing/auth và 7 Remote modules độc lập, chia sẻ thư viện UI nội bộ (@workspace/*).",
    "Hạ tầng Bare-metal K3s (arda-infra): Cụm 3 nodes (192.168.100.201-203), sử dụng Traefik ForwardAuth cho Ingress, CloudNativePG cho High Availability PostgreSQL cluster, và ArgoCD quản lý GitOps.",
  ],
  challenges: [
    "Xử lý phân tán authentication/authorization an toàn trên 9 services mà không tạo điểm nghẽn (bottleneck).",
    "Đồng bộ sự kiện tài chính giữa workflow engine (Zeebe) và finance service khi có sự cố mạng.",
    "Chia sẻ state và routing mượt mà giữa 7 React remotes mà không bị xung đột phiên bản dependencies.",
  ],
  solutions: [
    "Tích hợp Ory Kratos (quản lý danh tính/sessions) và Ory Hydra (OAuth2/OIDC token issuer), kết hợp ForwardAuth tại Traefik Ingress để kiểm tra token trước khi request vào microservice.",
    "Áp dụng NATS JetStream với Stream Deduplication và Idempotent Consumer handlers trong thư viện arda-events.",
    "Đóng gói core state & auth vào package chia sẻ @workspace/auth và @workspace/core, sử dụng Module Federation shared singleton dependencies.",
  ],
  outcomes: [
    "Hệ thống vận hành trơn tru trên cụm K3s homelab, tự động deploy qua ArgoCD mỗi khi merge code vào GitHub.",
    "Khả năng mở rộng service độc lập không ảnh hưởng tới toàn bộ hệ thống.",
  ],
  repositories: [
    { name: "arda-be (Backend Go Services)", url: "https://github.com/arda-labs/arda-be" },
    { name: "arda-mfe (React Module Federation)", url: "https://github.com/arda-labs/arda-mfe" },
    { name: "arda-infra (Kubernetes GitOps & Helm)", url: "https://github.com/arda-labs/arda-infra" },
  ],
  links: [
    { label: "Arda Labs Organization", url: "https://github.com/arda-labs" },
    { label: "Arda Website", url: "https://arda.io.vn" },
    { label: "Đọc bài phân tích kiến trúc Arda", url: "/writing/designing-arda-cloud-native-finops-platform" },
  ],
  evidence: [
    {
      id: "ev-arda-01",
      type: "github",
      claim: "Kinh nghiệm thực tế xây dựng Go Microservices & gRPC/NATS",
      statement: "Repo arda-be công khai trên GitHub gồm 9 Go services với gRPC contracts, Protobuf definitions và NATS JetStream outbox.",
      source: "https://github.com/arda-labs/arda-be",
      technologies: ["Go", "gRPC", "NATS JetStream", "Protobuf"],
      confidence: "verified",
    },
    {
      id: "ev-arda-02",
      type: "github",
      claim: "Kinh nghiệm vận hành Kubernetes K3s & GitOps ArgoCD",
      statement: "Repo arda-infra định nghĩa cấu hình K3s, CloudNativePG HA, Traefik ForwardAuth, và ArgoCD manifests.",
      source: "https://github.com/arda-labs/arda-infra",
      technologies: ["Kubernetes", "K3s", "ArgoCD", "CloudNativePG", "Traefik"],
      confidence: "verified",
    },
  ],
};
